openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 3.0.0
  title: Bybit Open API v5 explorer - Spot leverage token
tags:
  - name: etp
    description: ETP endpoints
    x-displayName: Spot Leverage Token
x-tagGroups:
  - name: private
    tags:
      - etp
paths:
  /v5/spot-lever-token/info:
    get:
      tags:
        - etp
      summary: Leverage Token Info
      description: Get lt information
      operationId: leverage-token-info
      parameters:
        - name: ltCoin
          in: query
          description: Levearage coin name. e.g., BTC3L
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-lever-token/reference:
    get:
      tags:
        - etp
      summary: LT Market
      description: Get lt market information
      operationId: leverage-token-reference
      parameters:
        - name: ltCoin
          in: query
          description: Levearage coin name. e.g., BTC3L
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/spot-lever-token/purchase:
    post:
      tags:
        - etp
      summary: Purchase
      description: Purchase leverage token
      operationId: purchase
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ltCoin:
                  type: string
                  description: Levearage coin name. e.g., BTC3L
                  example: EOS3L
                ltAmount:
                  type: string
                  description: Purchase amount
                  example: "100"
                serialNo:
                  type: string
                  description: Serial number, customised order id
                  example: test-001
                required:
                  - ltCoin
                  - ltAmount
  /v5/spot-lever-token/redeem:
    post:
      tags:
        - etp
      summary: Redeem
      description: Redeem leverage token
      operationId: redeem
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ltCoin:
                  type: string
                  description: Levearage coin name. e.g., BTC3L
                  example: EOS3L
                quantity:
                  type: string
                  description: Redeem quantity
                  example: "150"
                serialNo:
                  type: string
                  description: Serial number, customised order id
                  example: test-002
                required:
                  - ltCoin
                  - quantity
  /v5/spot-lever-token/order-record:
    get:
      tags:
        - etp
      summary: Purchase Or Redeem History
      description: Get the order history of purchase or redeem
      operationId: order-record
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: ltCoin
          in: query
          description: Levearage coin name. e.g., BTC3L
          required: false
          schema:
            type: string
        - name: orderId
          in: query
          description: Order id
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit size of each page. 1-500
          required: false
          schema:
            type: integer
            default: 100
        - name: ltOrderType
          in: query
          description: LT order type. 1=purchase, 2=redeem
          required: false
          schema:
            type: integer
            enum:
              - 1
              - 2
        - name: serialNo
          in: query
          description: Serial number
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation