openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of Position - v5 Restul API, which covers USDT Perpetual, USDC Perpetual, Inverse Perpetual, Inverse Future and Option.
  version: 3.0.0
  title: Bybit v5 position api explorer
tags:
  - name: position
    description: All Position v5 REST API.
    x-displayName: Position
paths:
  /v5/position/list:
    get:
      tags:
        - position
      summary: Get Position Info
      operationId: position-info
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Product type
          required: true
          schema:
            type: string
            enum:
              - linear
              - inverse
              - option
        - name: symbol
          in: query
          description: Symbol name
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin. For option only
          required: false
          schema:
            type: string
        - name: settleCoin
          in: query
          description: Used for linear & inverse, symbol or settleCoin is required
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: 1-200. max 200
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          description: cursor, used for pagination
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /v5/position/set-leverage:
    post:
      tags:
        - position
      summary: Set Leverage
      description: Set levearage.
      operationId: leverage
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                    - inverse
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: BTCUSDT
                buyLeverage:
                  type: string
                  description: Buy side leverage
                  example: "10"
                sellLeverage:
                  type: string
                  description: Sell side leverage
                  example: "10"
              required:
                - category
                - symbol
                - buyLevarge
                - sellLevarge
  /v5/position/switch-isolated:
    post:
      tags:
        - position
      summary: Switch Cross/Isolated Margin
      description: Select cross margin mode or isolated margin mode
      operationId: cross-isolate
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                    - inverse
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: BTCUSDT
                tradeMode:
                  type: integer
                  description: 0 - cross margin, 1 - isolated margin
                  enum:
                    - 0
                    - 1
                  example: 0
                buyLeverage:
                  type: string
                  description: Buy side leverage
                  example: "10"
                sellLeverage:
                  type: string
                  description: Sell side leverage
                  example: "10"
              required:
                - category
                - symbol
                - tradeMode
                - buyLevarge
                - sellLevarge

  /v5/position/set-tpsl-mode:
    post:
      tags:
        - position
      summary: Set TP/SL Mode
      description: Set tp/sl mode.
      operationId: tpsl-mode
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                    - inverse
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: ETHUSDT
                tpSlMode:
                  type: string
                  description: Full = full position TP/SL, Partial = partial mode tp/sl
                  enum:
                    - Full
                    - Partial
                  example: Full
              required:
                - category
                - symbol
                - tpSlMode

  /v5/position/switch-mode:
    post:
      tags:
        - position
      summary: Switch Position Mode
      description: Switch Position Mode
      operationId: position-mode
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                    - inverse
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: ETHUSDT
                coin:
                  type: string
                  description: Coin name
                  example: USDT
                mode:
                  type: integer
                  description: Position mode. 0 - Merged single, 3 - Both sides
                  enum:
                    - 0
                    - 3
                  example: 0
              required:
                - category
                - mode

  /v5/position/set-risk-limit:
    post:
      tags:
        - position
      summary: Set Risk Limit
      description: Set risk limit.
      operationId: set-risk-limit
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                    - inverse
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: BTCUSDT
                riskId:
                  type: integer
                  description: Risk limit id
                  example: 2
                positionIdx:
                  type: integer
                  description: Position index. 0=one-way-mode, 1=buy-hedge-mode, 2=sell-hedege-mode. <b>REQUIRED</b> for hedge-mode
                  enum:
                    - 0
                    - 1
                    - 2
                  example: 0
              required:
                - category
                - symbol
                - riskId

  /v5/position/trading-stop:
    post:
      tags:
        - position
      summary: Set Trading Stop
      description: Set trade stop.
      operationId: trading-stop
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                    - inverse
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: ETHUSDT
                takeProfit:
                  type: string
                  description: Take profit price
                  example: "1600"
                stopLoss:
                  type: string
                  description: Stop loss price
                  example: "1000"
                tpSize:
                  type: string
                  description: Take profit size
                  example:
                slSize:
                  type: string
                  description: Stop loss size
                  example:
                tpTriggerBy:
                  type: string
                  description: Take profit trigger price type
                  enum:
                    - LastPrice
                    - MarkPrice
                    - IndexPrice
                  example: MarkPrice
                slTriggerBy:
                  type: string
                  description: Stop loss trigger price type
                  enum:
                    - LastPrice
                    - MarkPrice
                    - IndexPrice
                  example: MarkPrice
                trailingStop:
                  type: string
                  description: Trailing stop
                  example:
                activePrice:
                  type: string
                  description: Trailing stop trigger price
                  example:
                positionIdx:
                  type: integer
                  description: Position index. 0=one-way-mode, 1=buy-hedge-mode, 2=sell-hedege-mode. <b>REQUIRED</b> for hedge-mode
                  enum:
                    - 0
                    - 1
                    - 2
                  example: 0
              required:
                - category
                - symbol
                - positionIdx

  /v5/position/set-auto-add-margin:
    post:
      tags:
        - position
      summary: Set Auto Add Margin
      description: Set Auto Add Margin
      operationId: add-margin
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Product type
                  enum:
                    - linear
                  example: linear
                symbol:
                  type: string
                  description: Symbol name
                  example: ETHUSDT
                autoAddMargin:
                  type: integer
                  description: 0 - turn on, 1 - turn off
                  example: 0
                positionIdx:
                  type: integer
                  description: Position index. 0=one-way-mode, 1=buy-hedge-mode, 2=sell-hedege-mode. <b>REQUIRED</b> for hedge-mode
                  enum:
                    - 0
                    - 1
                    - 2
                  example: 0
              required:
                - category
                - symbol
                - autoAddMargin
                - positionIdx

  /v5/execution/list:
    get:
      tags:
        - position
      summary: Get Execution (2 years)
      description: Get execution list
      operationId: execution
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Product type
          required: true
          schema:
            type: string
            enum:
              - linear
              - inverse
              - spot
              - option
        - name: symbol
          in: query
          description: Symbol name
          required: false
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin
          required: false
          schema:
            type: string
          example:
        - name: orderId
          in: query
          required: false
          schema:
            type: string
        - name: orderLinkId
          in: query
          description: User customised order id
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: execType
          in: query
          description: Execution type
          enum:
            - Trade
            - AdlTrade
            - Funding
            - BustTrade
            - Settle
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: 1-100. max 100
          required: false
          schema:
            type: integer
            default: 50
        - name: cursor
          in: query
          description: cursor to pagination
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /v5/position/closed-pnl:
    get:
      tags:
        - position
      summary: Get Closed PnL
      description: Get closed pnl
      operationId: close-pnl
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Product type
          required: true
          schema:
            type: string
            enum:
              - linear
              - inverse
        - name: symbol
          in: query
          description: Symbol name
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: 1-200. max 200
          required: false
          schema:
            type: integer
            default: 50
        - name: cursor
          in: query
          description: cursor for pagination
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation