/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  v3SideBar: [
    'v3/intro',
    {
      type: 'category',
      label: 'Tax',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v3/tax'
        }
      ]
    }
  ],
  p2pSideBar: [
    'p2p/guide',
    'p2p/all-balance',
    {
      type: 'category',
      label: 'Advertisement',
      items: [
        {
          type: 'autogenerated',
          dirName: 'p2p/ad'
        }
      ]
    },
    {
      type: 'category',
      label: 'Orders',
      items: [
        {
          type: 'autogenerated',
          dirName: 'p2p/order'
        }
      ]
    },
    {
      type: 'category',
      label: 'User',
      items: [
        {
          type: 'autogenerated',
          dirName: 'p2p/user'
        }
      ]
    }
  ],
  v5SideBar: [
    // 'v5/intro',
    'v5/guide',
    // 'v5/acct-mode',
    'v5/announcement',
    'v5/smp',
    'v5/copytrade',
    'v5/demo',
    'v5/system-status',
    {
      type: 'category',
      label: 'Market',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/market'
        }
      ]
    },
    {
      type: 'category',
      label: 'Trade',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/order'
        }
      ]
    },
    {
      type: 'category',
      label: 'Position',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/position'
        }
      ]
    },
    {
      type: 'category',
      label: 'Pre-upgrade',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/pre-upgrade'
        }
      ]
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/account'
        }
      ]
    },
    {
      type: 'category',
      label: 'Asset',
      items: [
        'v5/asset/delivery',
        'v5/asset/settlement',
        'v5/asset/exchange',
        'v5/asset/coin-info',
        'v5/asset/sub-uid-list',
        {
          type: 'category',
          label: 'Balances',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/balance'
            }
          ]
        },
        {
          type: 'category',
          label: 'Transfer',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/transfer'
            }
          ]
        },
        {
          type: 'category',
          label: 'Deposit',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/deposit'
            }
          ]
        },
        {
          type: 'category',
          label: 'Withdraw',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/withdraw'
            }
          ]
        },
        {
          type: 'category',
          label: 'Convert',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/convert'
            }
          ]
        },
        {
          type: 'category',
          label: 'Convert Small Balances',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/convert-small-balance'
            }
          ]
        },
        {
          type: 'category',
          label: 'Fiat-Convert',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/fiat-convert'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'User',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/user'
        }
      ]
    },
    {
      type: 'category',
      label: 'Spread Trading',
      items: [
        {
          type: 'category',
          label: 'Market',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/spread/market'
            }
          ]
        },
        {
          type: 'category',
          label: 'Trade',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/spread/trade'
            }
          ]
        },
        {
          type: 'category',
          label: 'Websocket Stream',
          items: [
            'v5/websocket/wss-authentication',
            {
              type: 'category',
              label: 'Public',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v5/spread/websocket/public'
                }
              ]
            },
            {
              type: 'category',
              label: 'Private',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v5/spread/websocket/private'
                }
              ]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'RFQ Trading',
      items: [
        'v5/rfq/basic-workflow',
        {
          type: 'category',
          label: 'Trade',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/rfq/trade'
            }
          ]
        },
        {
          type: 'category',
          label: 'WebSocket Stream',
          items: [
            'v5/websocket/wss-authentication',
            {
              type: 'category',
              label: 'Public',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v5/rfq/websocket/public'
                }
              ]
            },
            {
              type: 'category',
              label: 'Private',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v5/rfq/websocket/private'
                }
              ]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Affiliate',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/affiliate'
        }
      ]
    },
    // {
    //   type: 'category',
    //   label: 'Spot Leverage Token',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'v5/lt'
    //     }
    //   ]
    // },
    {
      type: 'category',
      label: 'Spot Margin Trade (UTA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/spot-margin-uta'
        }
      ]
    },
    {
      type: 'category',
      label: 'Crypto Loan (New)',
      items: [
        'v5/new-crypto-loan/loan-coin',
        'v5/new-crypto-loan/collateral-coin',
        'v5/new-crypto-loan/reduce-max-collateral-amt',
        'v5/new-crypto-loan/adjust-collateral',
        'v5/new-crypto-loan/ltv-adjust-history',
        'v5/new-crypto-loan/crypto-loan-position',
        'v5/new-crypto-loan/max-loan-amt',
        {
          type: 'category',
          label: 'Flexible Loan',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/new-crypto-loan/flexible'
            }
          ]
        },
        {
          type: 'category',
          label: 'Fixed Loan',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/new-crypto-loan/fixed'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Crypto Loan (legacy)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/crypto-loan'
        }
      ]
    },
    {
      type: 'category',
      label: 'Institutional Loan',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/otc'
        }
      ]
    },
    {
      type: 'category',
      label: 'Broker',
      items: [
        {
          type: 'category',
          label: 'API Broker',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/broker/api-broker'
            }
          ]
        },
        {
          type: 'category',
          label: 'Exchange Broker',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/broker/exchange-broker'
            },
            {
              type: 'category',
              label: 'Reward',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v5/broker/reward'
                }
              ]
            }
          ]
        },
        // 'v5/broker/exchange-broker/exchange-earning',
        // 'v5/broker/exchange-broker/account-info',
        // 'v5/broker/exchange-broker/sub-deposit-record',

      ]
    },
    {
      type: 'category',
      label: 'Earn',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/earn'
        }
      ]
    },
    {
      type: 'category',
      label: 'SBE',
      items: [
        'v5/sbe/sbe-basic-info',
        {
          type: 'category',
          label: 'BBO',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/sbe/bbo'
            }
          ]
        },
        {
          type: 'category',
          label: 'Level 50',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/sbe/level-50'
            }
          ]
        },
        {
          type: 'category',
          label: 'Public Trade',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/sbe/sbe-public-trade'
            }
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'WebSocket Stream',
      items: [
        'v5/websocket/wss-authentication',
        {
          type: 'category',
          label: 'Public',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/public'
            }
          ]
        },
        {
          type: 'category',
          label: 'Private',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/private'
            }
          ]
        },
        {
          type: 'category',
          label: 'Trade',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/trade'
            }
          ]
        },
        {
          type: 'category',
          label: 'System',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/system'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Rate Limit',
      items: [
        'v5/rate-limit/rate-limit',
        'v5/rate-limit/rules-for-vips',
        {
          type: 'category',
          label: 'API Rate Limit Rules for PROs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/rate-limit/rules-for-pros'
            }
          ]
        },
      ]
    },
    'v5/enum',
    'v5/error',
    {
      type: 'category',
      label: 'Abandoned Endpoints',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/abandon'
        }
      ]
    },
  ],
  apiExplorerSideBar: [
    {
      type: "category",
      label: "V5",
      link: {
        type: "generated-index",
        title: "V5 API",
        slug: "/api-explorer/v5/category/"
      },
      // @ts-ignore
      items: [
        require("./docs/api-explorer/v5/market/sidebar.js"),
        require("./docs/api-explorer/v5/trade/sidebar.js"),
        require("./docs/api-explorer/v5/position/sidebar.js"),
        require("./docs/api-explorer/v5/account/sidebar.js"),
        require("./docs/api-explorer/v5/asset/sidebar.js"),
        require("./docs/api-explorer/v5/user/sidebar.js"),
        require("./docs/api-explorer/v5/lt/sidebar.js"),
        require("./docs/api-explorer/v5/spot-margin-uta/sidebar.js"),
      ]
    }
  ],
  changelogSidebar: [
    "changelog/v5"
  ]
};

module.exports = sidebars;
