/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  derivatives: [
    {
      type: 'category',
      label: 'Rest API',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Market Data Endpoint',
          collapsed: true,
          items: [
            'derivatives/market/orderbook',
            'derivatives/market/kline',
            'derivatives/market/tickerInfo',
            'derivatives/market/instrumentInfo',
          ]
        },
        {
          type: 'category',
          label: 'Trade',
          collapsed: true,
          items: [
              'derivatives/trade/create-order'
          ]
        },
        {
          type: 'category',
          label: 'Account Asset',
          collapsed: true,
          items: [
            'derivatives/account/create-internal-transfer'
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Websocket',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Public Channel',
          collapsed: true,
          items: [
            'derivatives/websocket/orderbook'
          ]
        },
        {
          type: 'category',
          label: 'Private Channel',
          collapsed: true,
          items: [
            'derivatives/websocket/order'
          ]
        }
      ]
    }
  ],
  spot: [
    {
      type: 'category',
      label: 'Rest API',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Market Data Endpoint',
          collapsed: true,
          items: [
            'spot/market/symbolInfo',
            'spot/market/order-book'
          ]
        },
        {
          type: 'category',
          label: 'Trade',
          collapsed: true,
          items: [
            'spot/trade/create-order'
          ]
        },
        {
          type: 'category',
          label: 'Account Asset',
          collapsed: true,
          items: [
            'spot/account/create-internal-transfer'
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Websocket',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Public Channel',
          collapsed: true,
          items: [
            'spot/websocket/orderbook'
          ]
        },
        {
          type: 'category',
          label: 'Private Channel',
          collapsed: true,
          items: [
            'spot/websocket/order'
          ]
        }
      ]
    }
  ],
  copytrade: [
    {
      type: 'category',
      label: 'Rest API',
      collapsed: true,
      items: [
          'copy_trade/symbol-list'
      ]
    },
    {
      type: 'category',
      label: 'Websocket',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Public Channel',
          collapsed: true,
          items: [
            'copy_trade/websocket/orderbook'
          ]
        },
        {
          type: 'category',
          label: 'Private Channel',
          collapsed: true,
          items: [
            'copy_trade/websocket/order'
          ]
        }
      ]
    }
  ],
  usdc: [
    {
      type: 'category',
      label: 'Option',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Market Data Endpoint',
          items: [
            'usdc_contract/option/order-book'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'USDC Perpetual',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Market Data Endpoint',
          items: [
            'usdc_contract/perp/order-book'
          ]
        }
      ]
    }
  ],
  bestprac: [
    'best_practice/intro',
    {
      type: 'category',
      label: 'Broker',
      collapsed: true,
      items: [
          'best_practice/broker/broker_example'
      ]
    },
    {
      type: 'category',
      label: 'Copy Trade',
      collapsed: true,
      items: [
        'best_practice/copy_trade/copytrade_example'
      ]
    },
    {
      type: 'category',
      label: 'Derivatives',
      collapsed: true,
      items: [
        'best_practice/derivatives/derivatives_example'
      ]
    },
    {
      type: 'category',
      label: 'Spot',
      collapsed: true,
      items: [
        'best_practice/spot/spot_example'
      ]
    }
  ],
  changelog: [
      'changelog/example_01'
  ],
  labs: [
    'labs/example_01',
  ],
  contractSideBar: [
    {
      type: "category",
      label: "Contract V3",
      link: {
        type: "generated-index",
        title: "Contract API",
        description:
            "This is a sample api collection for contract",
        slug: "/category/contract-api"
      },
      // @ts-ignore
      items: require("./docs/api-explorer/contract/sidebar.js")
    }
  ]
};

module.exports = sidebars;